name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      uses: sumup/action-shellcheck@0.4.1
