name: Master CI
on:
  push:
    branches: [ master ]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      uses: sumup/action-shellcheck@0.4.1
    - name: Terraform security scan
      uses: sumup/terraform-security-scan@master
      with:
        tfsec_actions_comment: false
        tfsec_actions_working_dir: "test/"
        tfsec_exclude: "AWS018,AWS006,AWS004,AWS003,AZU003"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
